version: "3.8"
services:
  nginx:
    build:
      context: .
    ports:
      - 3000:80
    # copy source code to docker -> ghi đè thư mục build lên nginx
    volumes:
      - ../../jwt-frontend/build:/usr/share/nginx/html
      # fix react router
      - ./default.conf:/etc/nginx/conf.d/default.conf
