services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=decentralization
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3309:3306"
    # expose:
    #   - 3306
  backend:
    build:
      context: ../jwt-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_HOST=database-mysql
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.23.3
    ports:
      - 3000:80
    # copy source code to docker -> ghi đè thư mục build lên nginx
    volumes:
      - ../jwt-frontend/build:/usr/share/nginx/html
      # fix react router
      - ./default.conf:/etc/nginx/conf.d/default.conf
